Emptier tiles
GitTerraGame/Play-GitTerra-Action pull request #14
Opened 2024-05-03 23:14 UTC by AlexanderChernyshev

2024-05-04 02:29 UTC, sergeychernyshev requested changes
Minor fix for the tiles - see my comment below.

2024-05-04 02:29 UTC, sergeychernyshev commented on src/images/tiles/novaterraprime/novaterraprime_tile_17.svg
Looks like tiles 17 and 18 are not valid sprites - you have _ in the tile number, e.g. `id="tile_18"` instead of `id="tile18"`.

I fixed the code to fully ignore invalid tiles and to show an error message in the console.

2024-05-05 20:22 UTC, AlexanderChernyshev commented
Should be fixed. Let me know if there is another issue. Otherwise, just merge.

2024-05-06 21:07 UTC, sergeychernyshev approved these changes

2024-05-06 21:09 UTC, merged